{% set version = "0.10.0" %}

package:
  name: torchvision-base
  version: {{ version }}

source:
  fn: torchvision-{{ version }}.tar.gz
  url: https://github.com/pytorch/vision/archive/v{{ version }}.tar.gz
  sha256: 82bb2c2b03d8a65f4ea74bb0ee5566b0876a1992aceefb1e11475c7b5d2e857b
  patches:
    - 0101-find-ffmpeg-in-conda-env.patch
    - 0102-Fixed-failure-on-baremetal.patch
    - 0103-pick-up-ancaconda-gcc.patch

build:
  number: 1
  string: {{ build_type }}_py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }}   #[build_type == 'cpu']
  string: {{ build_type }}{{ cudatoolkit | replace(".*", "") }}_py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }} #[build_type == 'cuda']
  detect_binary_files_with_prefix: False
  script_env:
    - CUDA_HOME

requirements:
  build:
    - {{ compiler('cxx') }}
    - patch
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}
  host: 
    - future {{ future }}
    - python {{ python }}
    - cudatoolkit {{ cudatoolkit }}     # [build_type == 'cuda']
    - _pytorch_select  {{ pytorch_select_version }}
    - pytorch-base     {{ pytorch }}
    - setuptools {{ setuptools }}
    - ffmpeg {{ ffmpeg }}
    - av {{ av }}
    - libpng {{ libpng }}
    - jpeg {{ jpeg }}
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}

  run:
    - cudatoolkit {{ cudatoolkit }}     # [build_type == 'cuda']
    - future {{ future }}
    - numpy  {{ numpy }}
    - pillow {{ pillow }}
    - python {{ python }}
    - _pytorch_select  {{ pytorch_select_version }}
    - pytorch-base     {{ pytorch }}
    - six {{ six }}
    - ffmpeg                            # versioning handled by run_exports
    - av                                # versioning handled by run_exports
    - libpng                            # versioning handled by run_exports
    - jpeg                              # versioning handled by run_exports

about:
  home: http://pytorch.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Image and video datasets and models for torch deep learning
  description: |
    Popular datasets, model architectures, and common image transformations for computer vision
  dev_url: https://github.com/pytorch/vision
  doc_url: https://pytorch.org/docs/stable/torchvision/index.html 

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
