{% set version = "0.7.0" %}

package:
  name: torchvision-base
  version: {{ version }}

source:
  fn: torchvision-{{ version }}.tar.gz
  url: https://github.com/pytorch/vision/archive/v{{ version }}.tar.gz
  sha256: fa0a6f44a50451115d1499b3f2aa597e0092a07afce1068750260fa7dd2c85cb

build:
  number: 1
  string: {{ build_type }}_py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }}
  detect_binary_files_with_prefix: False

requirements:
  build:
    - {{ compiler('cxx') }}

  host: 
    - cudatoolkit-dev {{ cudatoolkit }} # [build_type == 'cuda']
    - future {{ future }}
    - python {{ python }}
    - _pytorch_select  {{ pytorch_select_version }}
    - pytorch-base     {{ pytorch }}
    - setuptools {{ setuptools }}

  run:
    - cudatoolkit {{ cudatoolkit }}     # [build_type == 'cuda']
    - future {{ future }}
    - numpy  {{ numpy }}
    - pillow {{ pillow }}
    - python {{ python }}
    - _pytorch_select  {{ pytorch_select_version }}
    - pytorch-base     {{ pytorch }}
    - six {{ six }}

about:
  home: http://pytorch.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Image and video datasets and models for torch deep learning
  description: |
    Popular datasets, model architectures, and common image transformations for computer vision
  dev_url: https://github.com/pytorch/vision
  doc_url: https://pytorch.org/docs/stable/torchvision/index.html 

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
