{% set version = "0.8.2" %}

package:
  name: torchvision-base
  version: {{ version }}

source:
  fn: torchvision-{{ version }}.tar.gz
  url: https://github.com/pytorch/vision/archive/v{{ version }}.tar.gz
  sha256: 9a866c3c8feb23b3221ce261e6153fc65a98ce9ceaa71ccad017016945c178bf 
  patches:
    - 0101-find-ffmpeg-in-conda-env.patch
    - 0102-Fixed-failure-on-baremetal.patch

build:
  number: 4
  string: {{ build_type }}_py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }}
  detect_binary_files_with_prefix: False
  script_env:
    - CUDA_HOME

requirements:
  build:
    - {{ compiler('cxx') }}
    - patch

  host: 
    - future {{ future }}
    - python {{ python }}
    - _pytorch_select  {{ pytorch_select_version }}
    - pytorch-base     {{ pytorch }}
    - setuptools {{ setuptools }}
    - ffmpeg {{ ffmpeg }}
    - av {{ av }}
    - libpng {{ libpng }}
    - jpeg {{ jpeg }}

  run:
    - cudatoolkit {{ cudatoolkit }}     # [build_type == 'cuda']
    - future {{ future }}
    - numpy  {{ numpy }}
    - pillow {{ pillow }}
    - python {{ python }}
    - _pytorch_select  {{ pytorch_select_version }}
    - pytorch-base     {{ pytorch }}
    - six {{ six }}
    - ffmpeg                            # versioning handled by run_exports
    - av                                # versioning handled by run_exports
    - libpng                            # versioning handled by run_exports
    - jpeg                              # versioning handled by run_exports

about:
  home: http://pytorch.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Image and video datasets and models for torch deep learning
  description: |
    Popular datasets, model architectures, and common image transformations for computer vision
  dev_url: https://github.com/pytorch/vision
  doc_url: https://pytorch.org/docs/stable/torchvision/index.html 

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
